### ISSUE TITLE
Pip installation

### ISSUE THREAD

**Issue by CodeCrow** [creafz/django-social-widgets#7]
When you install this using pip, as per the instructions, you get the error: 

Invalid template library specified. ImportError raised when trying to load 'social_widgets.templatetags.social_widgets': cannot import name Library

The code installed does not match the current master branch.

**Comment by creafz** [comment]
I have updated the PyPi version. Please try to install it now.

**Comment by CodeCrow** [comment]
Perfect.  Thank you!

**Comment by kalebtekle** [comment]
I get an error using django-social-widget: I am using Django 3.2.4
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'social_widgets.templatetags.social_widget
s': cannot import name 'Context' from 'django.template.base' (C:\Python39\lib\site-packages\django\template\base.py)
